import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'split_result.dart';

class PdfService {
  static Future<Uint8List> generateSplitPdf({
    required List<SplitResult> results,
    required double totalRent,
    String? address,
  }) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(48),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                    pw.Text('Split Fair', style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: const PdfColor.fromInt(0xFF1D9E75))),
                    pw.Text('Fair Rent Calculation', style: pw.TextStyle(fontSize: 14, color: PdfColors.grey600)),
                  ]),
                  pw.Text(_formatDate(DateTime.now()), style: pw.TextStyle(fontSize: 11)),
                ],
              ),
              pw.SizedBox(height: 6),
              pw.Divider(color: const PdfColor.fromInt(0xFF1D9E75), thickness: 2),
              pw.SizedBox(height: 24),
              pw.Container(
                padding: const pw.EdgeInsets.all(20),
                decoration: pw.BoxDecoration(color: const PdfColor.fromInt(0xFFE1F5EE), borderRadius: const pw.BorderRadius.all(pw.Radius.circular(12))),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Total Monthly Rent', style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                    pw.Text('\$${totalRent.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: const PdfColor.fromInt(0xFF0F6E56))),
                  ],
                ),
              ),
              pw.SizedBox(height: 28),
              pw.Table(
                border: pw.TableBorder(bottom: const pw.BorderSide(color: PdfColors.grey300), horizontalInside: const pw.BorderSide(color: PdfColors.grey200)),
                columnWidths: {0: const pw.FlexColumnWidth(2), 1: const pw.FlexColumnWidth(1.5), 2: const pw.FlexColumnWidth(1.2), 3: const pw.FlexColumnWidth(1.5)},
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: ['Tenant', 'Room', 'Share', 'Amount'].map((h) =>
                      pw.Padding(padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 10),
                        child: pw.Text(h, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700)))).toList(),
                  ),
                  ...results.map((r) => pw.TableRow(children: [
                    pw.Padding(padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 12), child: pw.Text(r.room.tenant, style: const pw.TextStyle(fontSize: 13))),
                    pw.Padding(padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 12), child: pw.Text('${r.room.name}\n${r.room.sqft.toInt()} sqft', style: const pw.TextStyle(fontSize: 11))),
                    pw.Padding(padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 12), child: pw.Text('${(r.percentage * 100).toStringAsFixed(1)}%', style: const pw.TextStyle(fontSize: 13))),
                    pw.Padding(padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 12), child: pw.Text('\$${r.amount.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: const PdfColor.fromInt(0xFF1D9E75)))),
                  ])),
                ],
              ),
              pw.Spacer(),
              pw.Divider(color: PdfColors.grey300),
              pw.SizedBox(height: 8),
              pw.Text('Generated by Split Fair', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey400)),
            ],
          );
        },
      ),
    );
    return pdf.save();
  }

  static String _formatDate(DateTime d) => '${d.month}/${d.day}/${d.year}';
}